version: "3.8"

services:
    react:
        stdin_open: true
        environment: 
            - CHOKIDAR_USEPOLLING=true
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3030:3000"
        volumes:
            - "/app/node_modules"
            - "./:/app"