"""empty message

Revision ID: 1e26eae6f460
Revises: 80d08836eff6
Create Date: 2020-09-18 13:49:36.791016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e26eae6f460'
down_revision = '80d08836eff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('group', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'updated_at')
    op.drop_column('group', 'created_at')
    # ### end Alembic commands ###
