"""empty message

Revision ID: 5797ca214c3b
Revises: 91abd3182f06
Create Date: 2020-09-18 14:41:24.420602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5797ca214c3b'
down_revision = '91abd3182f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lookalike', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('lookalike', 'creation_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lookalike', 'creation_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('lookalike', 'updated_at')
    # ### end Alembic commands ###
