"""empty message

Revision ID: 73f58e9016f7
Revises: 5797ca214c3b
Create Date: 2020-09-18 16:06:36.361247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f58e9016f7'
down_revision = '5797ca214c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('active', sa.Boolean(), nullable=True))
    op.execute("UPDATE domain SET active = true")
    op.alter_column('domain', 'active', nullable=False)
    op.add_column('domain', sa.Column('last_scanned', sa.DateTime(), nullable=True))
    op.add_column('domain', sa.Column('num_of_scans', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domain', 'num_of_scans')
    op.drop_column('domain', 'last_scanned')
    op.drop_column('domain', 'active')
    # ### end Alembic commands ###
