"""empty message

Revision ID: 812830621432
Revises: 73f58e9016f7
Create Date: 2020-09-21 10:45:42.274934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812830621432'
down_revision = '73f58e9016f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domain', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('status', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
