"""empty message

Revision ID: c4191feb177a
Revises: 42ea8cfe44dd
Create Date: 2020-09-24 10:06:44.678467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4191feb177a'
down_revision = '42ea8cfe44dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('start_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('domain', 'start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('start_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('domain', 'start_at')
    # ### end Alembic commands ###
