"""empty message

Revision ID: eb2461815d39
Revises: 223e9f8d9578
Create Date: 2020-09-11 11:31:30.295664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2461815d39'
down_revision = '223e9f8d9578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'name')
    # ### end Alembic commands ###
